service_name: travis-ci

and my travis.yml:

language: ruby
rvm:
- 2.4.5
- 1.9.3
env:
global:
- "JRUBY_OPTS=-Xcext.enabled=true"
- "CI=true"
- "TRAVIS=true"
- "HAS_JOSH_K_SEAL_OF_APPROVAL=true"
- "LANG=en_US.UTF-8"
- "LC_ALL=en_US.UTF-8"
- "RGV=master"
- "RGV=v2.0.2"

after_success:
- CI=true TRAVIS=true coveralls --verbose